PROMPTS = [
    '''What is cloud mining and how does it benefit mobile users in 2025?''',
    '''Is it safe to mine Bitcoin using mobile cloud mining apps?''',
    '''How to start earning Bitcoin without any investment using Bitcoin Cloud Mining?''',
    '''Beginner's guide to Bitcoin mining through cloud infrastructure in India.''',
    '''How Bitcoin Cloud Mining app helps save time and electricity.''',
    '''Top 5 benefits of using cloud mining vs traditional mining hardware.''',
    '''How secure is cloud-based mining for new crypto users?''',
    '''How to earn passive income with the Bitcoin Cloud Mining app.''',
    '''Bitcoin trends in 2025: Why cloud mining is the new standard.''',
    '''How students and freelancers are earning BTC from home via cloud mining.''',
    '''2025 में क्लाउड माइनिंग क्या है और यह मोबाइल उपयोगकर्ताओं के लिए कैसे फायदेमंद है?''',
    '''क्या मोबाइल क्लाउड माइनिंग ऐप्स से बिटकॉइन माइनिंग सुरक्षित है?''',
    '''बिना इन्वेस्टमेंट के Bitcoin Cloud Mining से बिटकॉइन कमाने की शुरुआत कैसे करें?''',
    '''भारत में क्लाउड माइनिंग के जरिए बिटकॉइन कमाने का शुरुआती गाइड।''',
    '''Bitcoin Cloud Mining ऐप कैसे समय और बिजली दोनों बचाता है?''',
    '''क्लाउड माइनिंग बनाम हार्डवेयर माइनिंग – आपके लिए बेहतर क्या है?''',
    '''क्या नए यूज़र्स के लिए क्लाउड माइनिंग सुरक्षित है?''',
    '''Bitcoin Cloud Mining ऐप से पॅसिव इनकम कैसे शुरू करें?''',
    '''2025 में बिटकॉइन के ट्रेंड्स – क्लाउड माइनिंग क्यों जरूरी है?''',
    '''स्टूडेंट्स और फ्रीलांसर्स कैसे घर बैठे बिटकॉइन कमा रहे हैं – जानिए क्लाउड माइनिंग का तरीका।''',
]
