name: Blogger Auto Poster

on:
  schedule:
    # Run daily at 9:00 AM UTC (2:30 PM IST)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  auto-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Blogger Auto Poster
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        BLOGGER_CREDENTIALS: ${{ secrets.BLOGGER_CREDENTIALS }}
      run: |
        python main.py
        
    - name: Notify on success
      if: success()
      run: |
        echo "✅ Blog posts generated and published successfully!"
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Blog posting failed!" 